### ISSUE TITLE
Prevent copyList window from getting cut off by edge of screen

### ISSUE THREAD

**Issue by austinthiel** [austinthiel/CopyMore#26]
jquery offers collision detection that "flips" menus if they collide with something

**Comment by austinthiel** [comment]
https://jqueryui.com/position/ may be the solution, @LandonHammond?

**Comment by LandonHammond** [comment]
If I understand correctly what the issue is, where your pointer position will cause the copylist window to open cut off by the edge of your monitor, jQuery won't help. jQuery can only see/manipulate the DOM which is rendered inside of the copylist window. What we would need to do is check the max cords of the screen size, take the width of the copylist window, and if the cursor position is within that space, set it to instead open at x-copylistwidth with ypos at cursor pos.

**Comment by austinthiel** [comment]
Merged a fix for the default screen. Will close for now and address later when we want to handle multiple screens.
